### ISSUE TITLE
Insert this.watchToken({  }) for newly deployed tokens

### ISSUE THREAD

**Issue by KelseyCarlow** [git-token/webhook-manager#3]
Web hook manager should connect to contract event listener service and send a `watch_token` event to the service when a new token is deployed.

Insert into `pingEvent.js` after successfully deploying the contract.

https://github.com/git-token/webhook-manager/blob/978b26d78e2e857a74ef9b935c8d0f0eedbee2dd/src/events/pingEvent.js#L21

**Comment by Ryanmtate** [comment]
https://github.com/git-token/webhook-manager/blob/master/src/events/pingEvent.js#L30
